// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Course struct {
	ID   int64
	Name string
}

type Module struct {
	ID       int64
	Name     string
	Folder   string
	CourseID pgtype.Int8
}

type Video struct {
	ID       int64
	Name     string
	VideoKey string
	ModuleID pgtype.Int8
}
