services:

  api:
    build: 
      context: .
      dockerfile: deploy/Dockerfile.api
    image: app
    container_name: videostr
    environment:
      - API_KEY=SeCrEt824
      - PORT=:8080
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./assets:/app/assets