package repositories

import (
	"encoding/json"
	"os"

	"github.com/ricardomdesa/videostr/domain"
)

// "../assets/media/mod.json"
func GetJsonConfig(filePath string) domain.AutoGenerated {

	mod := domain.AutoGenerated{}

	f, err := os.ReadFile(filePath)
	if err != nil {
		panic(err)
	}
	err = json.Unmarshal(f, &mod)
	if err != nil {
		panic(err)
	}
	return mod
}
