package repositories

import (
	"fmt"
	"os"
	"reflect"
	"testing"

	"github.com/ricardomdesa/videostr/domain"
)

func TestGetJsonConfig_SingleModule(t *testing.T) {

	f, err := os.CreateTemp("", "mod.json")
	if err != nil {
		panic(err)
	}
	defer func ()  {
		f.Close()
		os.Remove(f.Name())
	}()

	f.Write([]byte(`{"modulos": [{"name": "testes", "folder": "mod4", "videos": ["video1", "video2"]}]}`))

	expected := domain.AutoGenerated{

		Modulos: []struct {
			Name   string   `json:"name"`
			Folder string `json:"folder"`
			Videos []string `json:"videos"`
		}{
			{
				Name:   "testes",
				Folder: "mod4",
				Videos: []string{"video1", "video2"},
			},
		},
	}
	fmt.Println(expected)

	actual := GetJsonConfig(f.Name())

	if !reflect.DeepEqual(actual, expected) {
		t.Errorf("Expected %v, got %v", expected, actual)
	}
}
