apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: video-str
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: vapi2
        imagePullPolicy: IfNotPresent
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key
              key: sapikey
        ports:
        - containerPort: 8080

