// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo_sqlite

type Course struct {
	ID   int64
	Name string
}

type Module struct {
	ID       int64
	Name     string
	Folder   string
	CourseID int64
}

type Video struct {
	ID       int64
	Name     string
	VideoKey string
	ModuleID int64
}
