// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repo_sqlite

import (
	"context"
)

const addCourse = `-- name: AddCourse :exec
INSERT INTO courses (name) VALUES (?)
`

func (q *Queries) AddCourse(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, addCourse, name)
	return err
}

const addModule = `-- name: AddModule :exec
INSERT INTO modules (name, folder, course_id) VALUES (?, ?, ?)
`

type AddModuleParams struct {
	Name     string
	Folder   string
	CourseID int64
}

func (q *Queries) AddModule(ctx context.Context, arg AddModuleParams) error {
	_, err := q.db.ExecContext(ctx, addModule, arg.Name, arg.Folder, arg.CourseID)
	return err
}

const addVideo = `-- name: AddVideo :exec
INSERT INTO videos (name, video_key, module_id) VALUES (?, ?, ?)
`

type AddVideoParams struct {
	Name     string
	VideoKey string
	ModuleID int64
}

func (q *Queries) AddVideo(ctx context.Context, arg AddVideoParams) error {
	_, err := q.db.ExecContext(ctx, addVideo, arg.Name, arg.VideoKey, arg.ModuleID)
	return err
}

const getAllModules = `-- name: GetAllModules :many
SELECT id, name, folder, course_id FROM modules WHERE course_id = ?
`

func (q *Queries) GetAllModules(ctx context.Context, courseID int64) ([]Module, error) {
	rows, err := q.db.QueryContext(ctx, getAllModules, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Folder,
			&i.CourseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVideos = `-- name: GetAllVideos :many
SELECT m.name, c.name, v.id, v.name, v.video_key, v.module_id FROM videos v
join modules m on m.id = v.module_id
join courses c on c.id = m.course_id
WHERE c.id = ?
`

type GetAllVideosRow struct {
	Name     string
	Name_2   string
	ID       int64
	Name_3   string
	VideoKey string
	ModuleID int64
}

func (q *Queries) GetAllVideos(ctx context.Context, id int64) ([]GetAllVideosRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllVideos, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllVideosRow
	for rows.Next() {
		var i GetAllVideosRow
		if err := rows.Scan(
			&i.Name,
			&i.Name_2,
			&i.ID,
			&i.Name_3,
			&i.VideoKey,
			&i.ModuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourses = `-- name: GetCourses :many
SELECT id, name FROM courses
`

func (q *Queries) GetCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.QueryContext(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
